# Jekyll configuration for focusnonprofit.com
url: "https://focusnonprofit.com"
# baseurl removed for custom domain deployment
# Add any other config options below as needed

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/
  pages:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
